Sp 5061
kenny26ru/schoolportal pull request #4
Opened 2022-01-11 14:53 UTC by Toxa1456

Sp 5061 - добавить модель директор

2022-01-11 17:01 UTC, dmtch-github requested changes
Реализуй сеттеры и геттеры через lombok. Явное описание методов убери.

2022-01-11 17:08 UTC, kenny26ru commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +    @Column(name = "id", nullable = false)
Аннотация column не нужна 
Поставь лучше аннотацию generateValue

2022-01-11 18:11 UTC, Toxa1456 commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +    @Column(name = "id", nullable = false)
Хорошо, сделано

2022-01-11 18:26 UTC, dmtch-github commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +    @Getter @Setter
@Getter @Setter лучше указывать для класса, тогда ты сможешь добавлять новые поля без повторения этих аннотаций.

2022-01-11 18:37 UTC, Toxa1456 commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +    @Getter @Setter
Хорошо, перенес на класс

2022-01-11 19:34 UTC, kenny26ru commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +
в конструкторе вызвать поля класса Person

2022-01-11 19:34 UTC, kenny26ru commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +
и для Entity нужен пустой конструктор, воспользуйся ломбоком

2022-01-12 07:59 UTC, kenny26ru commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +        setFirstName(firstName);
здесь должен быть не set а super

2022-01-12 07:59 UTC, kenny26ru commented
также необходимо спулиться и решить конфликты

2022-01-12 09:21 UTC, Toxa1456 commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +        setFirstName(firstName);
А как мне использовать super, если в классе персон нет конструктора и все поля приватные?

2022-01-12 09:33 UTC, Toxa1456 commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Director.java
> +        setFirstName(firstName);
А почему в файле pom закоментили "spring-boot-starter-data-jpa", без этой зависимости вообще Entity не работает

2022-01-12 14:45 UTC, kenny26ru commented
исправить конфликты

2022-01-12 17:33 UTC, kenny26ru commented on src/main/java/com/kataacademy/schoolportal/common/models/persons/Person.java
> -@MappedSuperclass
надо вернуть обратно, эта аннотация нужна

2022-01-12 17:58 UTC, merged